#!/usr/bin/env python3
################################################################################
#         Copyright 2023 Lawrence Livermore National Security, LLC             #
#         See the top-level LICENSE file for details.                          #
#                                                                              #
#         SPDX-License-Identifier: MIT                                         #
################################################################################

"""
Generate expected output CSV files for the scale/ test suite.

Mirrors generate_all_expected_outputs.py (which does this for comprehensive/)
but for tests/test_traces/scale/. Uses the same verified Python reference
implementation (scripts/python_reference_scheduler.py) as the oracle, for
consistency with how comprehensive/'s expected files are produced - see
tests/README.md, "Expected outputs are generated by Python reference
implementation, not hand-calculated."

Background: scale/'s expected_output.csv and expected_resources.csv files
were never covered by any generator script. They appear to be leftovers
from an earlier, abandoned test-suite design (see the now-removed
tests/test_traces/correctness/ scheme referenced by
generate_correctness_traces.py / generate_all_analytical_oracles.py /
verify_against_analytical.py, whose "1 medium + 3 large cross-validation
tests, 50-2000 jobs" naming - small_10jobs, medium_50jobs, large_100/200jobs,
xlarge_500jobs, huge_2000jobs - matches scale/'s file names exactly). When
the test suite moved to today's comprehensive/ + generators/ design, scale/
was never migrated onto it, so its expected files were left stale,
partially computed, or copy-pasted between differently-sized tests.

NOTE ON NODE COUNT: unlike comprehensive/ (100 nodes), scale/'s own job
sizes only make sense at TOTAL_NODES = 795 - the actual dr_evt default
(see src/dr_evt_types.hpp). Several scale/ jobs request as many as 497
nodes, which cannot be scheduled at all under 100 nodes. Confirmed
empirically earlier: running these traces at --total_nodes 100 causes
jobs to silently never start ("Jobs completed: 4/50" for medium_50jobs.csv
specifically), which is what produced the original broken/incomplete
expected files this script replaces.

FIXED (previously a known limitation): xlarge_500jobs.csv and
huge_2000jobs.csv have been rebuilt with fresh, complete input data
(500 and 2000 jobs respectively, generated via scripts/generators/generate_large_test.py
with total_nodes=795) and are now included in TESTS below.
xlarge_500jobs_v2.csv has been removed entirely - it was an unreferenced
duplicate (nothing in the codebase or test scripts used it, only the
plain xlarge_500jobs.csv is referenced, e.g. by test_fcfs_comprehensive.sh),
not a genuinely distinct second variant.
"""

import sys
import csv
from pathlib import Path

# Resolve paths relative to this script's own location, not the caller's
# current working directory - the previous sys.path.append('../scripts')
# and TRACE_DIR = Path("../tests/...") only worked if invoked from inside
# scripts/ itself, failing with ModuleNotFoundError when run from the
# repo root or anywhere else (confirmed: python3
# scripts/generators/generate_scale_expected_outputs.py from the repo
# root failed this way).
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent  # scripts/generators -> scripts -> repo root

sys.path.append(str(REPO_ROOT / "scripts"))
from python_reference_scheduler import EasyBackfillingScheduler, Job

TRACE_DIR = REPO_ROOT / "tests" / "test_traces" / "scale"
TOTAL_NODES = 795  # matches src/dr_evt_types.hpp's default, NOT comprehensive/'s 100

TESTS = [
    "small_10jobs",
    "medium_50jobs",
    "large_100jobs",
    "large_200jobs",
    "xlarge_500jobs",
    "huge_2000jobs",
]


def load_trace(filename):
    """Load trace file into Job objects."""
    jobs = []
    with open(filename, 'r') as f:
        reader = csv.DictReader(f)
        for idx, row in enumerate(reader):
            actual_run_time = float(row.get('actual_run_time', row['time_limit']))
            jobs.append(Job(
                idx=idx,
                submit_time=float(row['job_submit_time']),
                nodes=int(row['num_nodes']),
                duration=float(row['time_limit']),
                actual_run_time=actual_run_time
            ))
    return jobs


def generate_expected_output(test_id):
    """Generate expected output for a test."""
    input_file = TRACE_DIR / f"{test_id}.csv"
    output_file = TRACE_DIR / f"{test_id}.expected_output.csv"
    resource_file = TRACE_DIR / f"{test_id}.expected_resources.csv"

    if not input_file.exists():
        print(f"\u2717 {test_id} - Input file not found")
        return False

    try:
        jobs = load_trace(input_file)

        scheduler = EasyBackfillingScheduler(TOTAL_NODES, verbose=False)
        result = scheduler.simulate(jobs)

        # Sanity check: every job must have actually been scheduled.
        # This is exactly the failure mode that produced the original
        # broken files (jobs silently left with start_time/end_time
        # unset because they never fit under the wrong node count) -
        # refuse to write a file that would repeat that mistake instead
        # of writing partial/placeholder data silently.
        unscheduled = [job.idx for job in result if job.start_time is None]
        if unscheduled:
            print(f"\u2717 {test_id} - {len(unscheduled)} job(s) never scheduled "
                  f"(job indices: {unscheduled[:10]}{'...' if len(unscheduled) > 10 else ''}) "
                  f"- refusing to write incomplete expected output")
            return False

        with open(output_file, 'w') as f:
            f.write("job_id,start_time,end_time\n")
            for job in result:
                f.write(f"{job.idx},{int(job.start_time)},{int(job.end_time)}\n")

        with open(resource_file, 'w') as f:
            f.write("time,nodes_used,nodes_free,running_jobs\n")
            for time, nodes_used, nodes_free, running_jobs in scheduler.resource_timeline:
                f.write(f"{int(time)},{nodes_used},{nodes_free},{running_jobs}\n")

        print(f"\u2713 {test_id} - Generated ({len(result)} jobs, "
              f"{len(scheduler.resource_timeline)} resource events)")
        return True

    except Exception as e:
        print(f"\u2717 {test_id} - Error: {e}")
        return False


def main():
    """Generate all expected outputs for scale/."""
    print("=" * 60)
    print("Generating scale/ Expected Outputs from Python Reference")
    print(f"(TOTAL_NODES = {TOTAL_NODES})")
    print("=" * 60)
    print()

    success = 0
    failed = 0

    for test_id in TESTS:
        if generate_expected_output(test_id):
            success += 1
        else:
            failed += 1

    print()
    print("=" * 60)
    print(f"Generated: {success}/{len(TESTS)}")
    if failed > 0:
        print(f"Failed: {failed}")
    print("=" * 60)

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
