# Read the Docs configuration file

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py

# Python configuration
python:
  version: "3.9"
  install:
    - requirements: docs/requirements.txt

# Build formats
formats:
  - pdf
  - htmlzip
  - epub
